/**
 * NeDB-compatible document model, query matcher and update engine.
 *
 * This is a TypeScript port of the relevant parts of `@seald-io/nedb`'s
 * `lib/model.js` and `lib/utils.js` (MIT licensed, https://github.com/seald/nedb).
 * It is kept semantically identical on purpose: the SQLite backend evaluates
 * queries/updates with these functions so that plugin-visible behaviour matches
 * the old NeDB store one to one.
 *
 * Ported functions: checkObject/checkKey, serialize/deserialize, deepCopy,
 * compareThings, areThingsEqual, getDotValue(s), match/matchQueryPart, modify
 * (all update modifiers) and uid().
 */

import { randomBytes } from 'crypto';

// ==============================================================
// utils (from lib/utils.js)
// ==============================================================

export const uniq = <T>(array: T[], iteratee?: (x: T) => any): T[] => {
  if (iteratee) return [...new Map(array.map(x => [iteratee(x), x])).values()];
  return [...new Set(array)];
};

const isObject = (arg: any): boolean => typeof arg === 'object' && arg !== null;

export const isDate = (d: any): d is Date =>
  isObject(d) && Object.prototype.toString.call(d) === '[object Date]';

export const isRegExp = (re: any): re is RegExp =>
  isObject(re) && Object.prototype.toString.call(re) === '[object RegExp]';

/**
 * Random alphanumerical string, same algorithm as NeDB's customUtils.uid.
 */
export const uid = (len: number): string =>
  randomBytes(Math.ceil(Math.max(8, len * 2)))
    .toString('base64')
    .replace(/[+/]/g, '')
    .slice(0, len);

// ==============================================================
// Keys / documents
// ==============================================================

const checkKey = (k: string | number, v: any): void => {
  if (typeof k === 'number') k = k.toString();

  if (
    k[0] === '$' &&
    !(k === '$$date' && typeof v === 'number') &&
    !(k === '$$deleted' && v === true) &&
    !k.startsWith('$$indexCreated') &&
    !k.startsWith('$$indexRemoved')
  )
    throw new Error('Field names cannot begin with the $ character');

  if (k.indexOf('.') !== -1) throw new Error('Field names cannot contain a .');
};

/**
 * Check a DB object and throw an error if it's not valid.
 * Works by applying the above checkKey function to all fields recursively.
 */
export const checkObject = (obj: any): void => {
  if (Array.isArray(obj)) {
    obj.forEach(o => {
      checkObject(o);
    });
  }

  if (typeof obj === 'object' && obj !== null) {
    for (const k in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, k)) {
        checkKey(k, obj[k]);
        checkObject(obj[k]);
      }
    }
  }
};

/**
 * Serialize an object to be persisted to a one-line string.
 * Dates become `{ $$date: <ms> }`, undefined fields are dropped.
 */
export const serialize = (obj: any): string =>
  JSON.stringify(obj, function (this: any, k: string, v: any) {
    checkKey(k, v);

    if (v === undefined) return undefined;
    if (v === null) return null;

    // Hackish way of checking if object is Date (this way it works between
    // execution contexts). We can't use value directly because for dates it is
    // already string in this function (date.toJSON was already called).
    if (typeof this[k].getTime === 'function') return { $$date: this[k].getTime() };

    return v;
  });

/**
 * From a one-line representation of an object generated by the serialize
 * function, return the object itself.
 */
export const deserialize = (rawData: string): any =>
  JSON.parse(rawData, function (k: string, v: any) {
    if (k === '$$date') return new Date(v);
    if (
      typeof v === 'string' ||
      typeof v === 'number' ||
      typeof v === 'boolean' ||
      v === null
    )
      return v;
    if (v && v.$$date) return v.$$date;

    return v;
  });

/**
 * Deep copy a DB object.
 */
export const deepCopy = (obj: any, strictKeys?: boolean): any => {
  if (typeof obj === 'boolean' || typeof obj === 'number' || typeof obj === 'string' || obj === null || isDate(obj))
    return obj;

  if (Array.isArray(obj)) return obj.map(o => deepCopy(o, strictKeys));

  if (typeof obj === 'object') {
    const res: any = {};
    for (const k in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, k) && (!strictKeys || (k[0] !== '$' && k.indexOf('.') === -1))) {
        res[k] = deepCopy(obj[k], strictKeys);
      }
    }
    return res;
  }

  return undefined;
};

export const isPrimitiveType = (obj: any): boolean =>
  typeof obj === 'boolean' || typeof obj === 'number' || typeof obj === 'string' || obj === null || isDate(obj) || Array.isArray(obj);

// ==============================================================
// Comparison
// ==============================================================

const compareNSB = (a: number | string | boolean, b: number | string | boolean): number => {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
};

const compareArrays = (a: any[], b: any[]): number => {
  const minLength = Math.min(a.length, b.length);
  for (let i = 0; i < minLength; i += 1) {
    const comp = compareThings(a[i], b[i]);
    if (comp !== 0) return comp;
  }
  return compareNSB(a.length, b.length);
};

/**
 * Compare { things U undefined }.
 * Type hierarchy: undefined, null, number, string, boolean, date, array, object.
 */
export const compareThings = (a: any, b: any, _compareStrings?: (a: string, b: string) => number): number => {
  const compareStrings = _compareStrings || compareNSB;

  // undefined
  if (a === undefined) return b === undefined ? 0 : -1;
  if (b === undefined) return 1;

  // null
  if (a === null) return b === null ? 0 : -1;
  if (b === null) return 1;

  // Numbers
  if (typeof a === 'number') return typeof b === 'number' ? compareNSB(a, b) : -1;
  if (typeof b === 'number') return typeof a === 'number' ? compareNSB(a, b) : 1;

  // Strings
  if (typeof a === 'string') return typeof b === 'string' ? compareStrings(a, b) : -1;
  if (typeof b === 'string') return typeof a === 'string' ? compareStrings(a, b) : 1;

  // Booleans
  if (typeof a === 'boolean') return typeof b === 'boolean' ? compareNSB(a, b) : -1;
  if (typeof b === 'boolean') return typeof a === 'boolean' ? compareNSB(a, b) : 1;

  // Dates
  if (isDate(a)) return isDate(b) ? compareNSB(a.getTime(), b.getTime()) : -1;
  if (isDate(b)) return isDate(a) ? compareNSB(a.getTime(), b.getTime()) : 1;

  // Arrays (first element is most significant and so on)
  if (Array.isArray(a)) return Array.isArray(b) ? compareArrays(a, b) : -1;
  if (Array.isArray(b)) return Array.isArray(a) ? compareArrays(a, b) : 1;

  // Objects
  const aKeys = Object.keys(a).sort();
  const bKeys = Object.keys(b).sort();

  for (let i = 0; i < Math.min(aKeys.length, bKeys.length); i += 1) {
    const comp = compareThings(a[aKeys[i]], b[bKeys[i]]);
    if (comp !== 0) return comp;
  }

  return compareNSB(aKeys.length, bKeys.length);
};

/**
 * Check whether 'things' are equal.
 */
export const areThingsEqual = (a: any, b: any): boolean => {
  // Strings, booleans, numbers, null
  if (
    a === null ||
    typeof a === 'string' ||
    typeof a === 'boolean' ||
    typeof a === 'number' ||
    b === null ||
    typeof b === 'string' ||
    typeof b === 'boolean' ||
    typeof b === 'number'
  )
    return a === b;

  // Dates
  if (isDate(a) || isDate(b)) return isDate(a) && isDate(b) && a.getTime() === b.getTime();

  // Arrays (no match since arrays are used as a $in)
  // undefined (no match since they mean field doesn't exist and can't be serialized)
  if (
    (!(Array.isArray(a) && Array.isArray(b)) && (Array.isArray(a) || Array.isArray(b))) ||
    a === undefined ||
    b === undefined
  )
    return false;

  // General objects (check for deep equality)
  let aKeys: string[];
  let bKeys: string[];
  try {
    aKeys = Object.keys(a);
    bKeys = Object.keys(b);
  } catch (e) {
    return false;
  }

  if (aKeys.length !== bKeys.length) return false;
  for (const el of aKeys) {
    if (bKeys.indexOf(el) === -1) return false;
    if (!areThingsEqual(a[el], b[el])) return false;
  }
  return true;
};

// ==============================================================
// Updating documents
// ==============================================================

type ModifierFunction = (obj: any, field: any, value: any) => void;

const createModifierFunction =
  (lastStepModifierFunction: ModifierFunction, unset = false): ModifierFunction =>
  (obj: any, field: any, value: any) => {
    const func = (obj: any, field: any, value: any): void => {
      const fieldParts = typeof field === 'string' ? field.split('.') : field;

      if (fieldParts.length === 1) lastStepModifierFunction(obj, field, value);
      else {
        if (obj[fieldParts[0]] === undefined) {
          if (unset) return;
          obj[fieldParts[0]] = {};
        }
        func(obj[fieldParts[0]], fieldParts.slice(1), value);
      }
    };
    return func(obj, field, value);
  };

const $addToSetPartial = (obj: any, field: any, value: any): void => {
  // Create the array if it doesn't exist
  if (!Object.prototype.hasOwnProperty.call(obj, field)) {
    obj[field] = [];
  }

  if (!Array.isArray(obj[field])) throw new Error("Can't $addToSet an element on non-array values");

  if (value !== null && typeof value === 'object' && value.$each) {
    if (Object.keys(value).length > 1) throw new Error("Can't use another field in conjunction with $each");
    if (!Array.isArray(value.$each)) throw new Error('$each requires an array value');

    value.$each.forEach((v: any) => {
      $addToSetPartial(obj, field, v);
    });
  } else {
    let addToSet = true;
    obj[field].forEach((v: any) => {
      if (compareThings(v, value) === 0) addToSet = false;
    });
    if (addToSet) obj[field].push(value);
  }
};

const modifierFunctions: Record<string, ModifierFunction> = {
  $set: createModifierFunction((obj, field, value) => {
    obj[field] = value;
  }),
  $unset: createModifierFunction((obj, field, value) => {
    delete obj[field];
  }, true),
  $min: createModifierFunction((obj, field, value) => {
    if (typeof obj[field] === 'undefined') obj[field] = value;
    else if (value < obj[field]) obj[field] = value;
  }),
  $max: createModifierFunction((obj, field, value) => {
    if (typeof obj[field] === 'undefined') obj[field] = value;
    else if (value > obj[field]) obj[field] = value;
  }),
  $inc: createModifierFunction((obj, field, value) => {
    if (typeof value !== 'number') throw new Error(`${value} must be a number`);

    if (typeof obj[field] !== 'number') {
      if (!Object.prototype.hasOwnProperty.call(obj, field)) obj[field] = value;
      else throw new Error("Don't use the $inc modifier on non-number fields");
    } else obj[field] += value;
  }),
  $pull: createModifierFunction((obj, field, value) => {
    if (!Array.isArray(obj[field])) throw new Error("Can't $pull an element from non-array values");

    const arr = obj[field];
    for (let i = arr.length - 1; i >= 0; i -= 1) {
      if (match(arr[i], value)) arr.splice(i, 1);
    }
  }),
  $pop: createModifierFunction((obj, field, value) => {
    if (!Array.isArray(obj[field])) throw new Error("Can't $pop an element from non-array values");
    if (typeof value !== 'number') throw new Error(`${value} isn't an integer, can't use it with $pop`);
    if (value === 0) return;

    if (value > 0) obj[field] = obj[field].slice(0, obj[field].length - 1);
    else obj[field] = obj[field].slice(1);
  }),
  $addToSet: createModifierFunction($addToSetPartial),
  $push: createModifierFunction((obj, field, value) => {
    // Create the array if it doesn't exist
    if (!Object.prototype.hasOwnProperty.call(obj, field)) obj[field] = [];

    if (!Array.isArray(obj[field])) throw new Error("Can't $push an element on non-array values");

    if (value !== null && typeof value === 'object' && value.$slice && value.$each === undefined) value.$each = [];

    if (value !== null && typeof value === 'object' && value.$each) {
      if (Object.keys(value).length >= 3 || (Object.keys(value).length === 2 && value.$slice === undefined))
        throw new Error('Can only use $slice in cunjunction with $each when $push to array');
      if (!Array.isArray(value.$each)) throw new Error('$each requires an array value');

      value.$each.forEach((v: any) => {
        obj[field].push(v);
      });

      if (value.$slice === undefined || typeof value.$slice !== 'number') return;

      if (value.$slice === 0) obj[field] = [];
      else {
        let start: number;
        let end: number;
        const n = obj[field].length;
        if (value.$slice < 0) {
          start = Math.max(0, n + value.$slice);
          end = n;
        } else {
          start = 0;
          end = Math.min(n, value.$slice);
        }
        obj[field] = obj[field].slice(start, end);
      }
    } else {
      obj[field].push(value);
    }
  }),
};

/**
 * Modify a DB object according to an update query.
 */
export const modify = (obj: any, updateQuery: any): any => {
  const keys = Object.keys(updateQuery);
  const firstChars = keys.map(item => item[0]);
  const dollarFirstChars = firstChars.filter(c => c === '$');
  let newDoc: any;
  let modifiers: string[];

  if (keys.indexOf('_id') !== -1 && updateQuery._id !== obj._id)
    throw new Error("You cannot change a document's _id");

  if (dollarFirstChars.length !== 0 && dollarFirstChars.length !== firstChars.length)
    throw new Error('You cannot mix modifiers and normal fields');

  if (dollarFirstChars.length === 0) {
    // Simply replace the object with the update query contents
    newDoc = deepCopy(updateQuery);
    newDoc._id = obj._id;
  } else {
    // Apply modifiers
    modifiers = uniq(keys);
    newDoc = deepCopy(obj);
    modifiers.forEach(m => {
      if (!modifierFunctions[m]) throw new Error(`Unknown modifier ${m}`);

      if (typeof updateQuery[m] !== 'object') throw new Error(`Modifier ${m}'s argument must be an object`);

      const keys = Object.keys(updateQuery[m]);
      keys.forEach(k => {
        modifierFunctions[m](newDoc, k, updateQuery[m][k]);
      });
    });
  }

  // Check result is valid and return it
  checkObject(newDoc);

  if (obj._id !== newDoc._id) throw new Error("You can't change a document's _id");
  return newDoc;
};

// ==============================================================
// Finding documents
// ==============================================================

/**
 * Get a value from object with dot notation.
 */
export const getDotValue = (obj: any, field: any): any => {
  const fieldParts = typeof field === 'string' ? field.split('.') : field;

  if (!obj) return undefined; // field cannot be empty so that means we should return undefined so that nothing can match

  if (fieldParts.length === 0) return obj;

  if (fieldParts.length === 1) return obj[fieldParts[0]];

  if (Array.isArray(obj[fieldParts[0]])) {
    // If the next field is an integer, return only this item of the array
    const i = parseInt(fieldParts[1], 10);
    if (typeof i === 'number' && !isNaN(i)) return getDotValue(obj[fieldParts[0]][i], fieldParts.slice(2));

    // Return the array of values
    return obj[fieldParts[0]].map((el: any) => getDotValue(el, fieldParts.slice(1)));
  } else return getDotValue(obj[fieldParts[0]], fieldParts.slice(1));
};

/**
 * Get dot values for either a bunch of fields or just one.
 */
export const getDotValues = (obj: any, fields: any): any => {
  if (!Array.isArray(fields)) throw new Error('fields must be an Array');
  if (fields.length > 1) {
    const key: any = {};
    for (const field of fields) {
      key[field] = getDotValue(obj, field);
    }
    return key;
  } else return getDotValue(obj, fields[0]);
};

const areComparable = (a: any, b: any): boolean => {
  if (
    typeof a !== 'string' &&
    typeof a !== 'number' &&
    !isDate(a) &&
    typeof b !== 'string' &&
    typeof b !== 'number' &&
    !isDate(b)
  )
    return false;

  if (typeof a !== typeof b) return false;

  return true;
};

type ComparisonFunction = (a: any, b: any) => boolean;

const comparisonFunctions: Record<string, ComparisonFunction> = {
  $lt: (a, b) => areComparable(a, b) && a < b,
  $lte: (a, b) => areComparable(a, b) && a <= b,
  $gt: (a, b) => areComparable(a, b) && a > b,
  $gte: (a, b) => areComparable(a, b) && a >= b,
  $ne: (a, b) => a === undefined || !areThingsEqual(a, b),
  $in: (a, b) => {
    if (!Array.isArray(b)) throw new Error('$in operator called with a non-array');

    for (const el of b) {
      if (areThingsEqual(a, el)) return true;
    }

    return false;
  },
  $nin: (a, b) => {
    if (!Array.isArray(b)) throw new Error('$nin operator called with a non-array');

    return !comparisonFunctions.$in(a, b);
  },
  $regex: (a, b) => {
    if (!isRegExp(b)) throw new Error('$regex operator called with non regular expression');

    if (typeof a !== 'string') return false;
    else return b.test(a);
  },
  $exists: (a, b) => {
    // This will be true for all values of stat except false, null, undefined and 0
    // That's strange behaviour (we should only use true/false) but that's the way Mongo does it...
    if (b || b === '') b = true;
    else b = false;

    if (a === undefined) return !b;
    else return b;
  },
  $size: (a, b) => {
    if (!Array.isArray(a)) return false;
    if (b % 1 !== 0) throw new Error('$size operator called without an integer');

    return a.length === b;
  },
  $elemMatch: (a, b) => {
    if (!Array.isArray(a)) return false;
    return a.some(el => match(el, b));
  },
};

const arrayComparisonFunctions: Record<string, boolean> = { $size: true, $elemMatch: true };

const logicalOperators: Record<string, (obj: any, query: any) => boolean> = {
  $or: (obj, query) => {
    if (!Array.isArray(query)) throw new Error('$or operator used without an array');

    for (let i = 0; i < query.length; i += 1) {
      if (match(obj, query[i])) return true;
    }

    return false;
  },
  $and: (obj, query) => {
    if (!Array.isArray(query)) throw new Error('$and operator used without an array');

    for (let i = 0; i < query.length; i += 1) {
      if (!match(obj, query[i])) return false;
    }

    return true;
  },
  $not: (obj, query) => !match(obj, query),
  $where: (obj, fn) => {
    if (typeof fn !== 'function') throw new Error('$where operator used without a function');

    const result = fn.call(obj);
    if (typeof result !== 'boolean') throw new Error('$where function must return boolean');

    return result;
  },
};

/**
 * Tell if a given document matches a query.
 */
export const match = (obj: any, query: any): boolean => {
  // Primitive query against a primitive type
  if (isPrimitiveType(obj) || isPrimitiveType(query)) return matchQueryPart({ needAKey: obj }, 'needAKey', query);

  // Normal query
  for (const queryKey in query) {
    if (Object.prototype.hasOwnProperty.call(query, queryKey)) {
      const queryValue = query[queryKey];
      if (queryKey[0] === '$') {
        if (!logicalOperators[queryKey]) throw new Error(`Unknown logical operator ${queryKey}`);
        if (!logicalOperators[queryKey](obj, queryValue)) return false;
      } else if (!matchQueryPart(obj, queryKey, queryValue)) return false;
    }
  }

  return true;
};

/**
 * Match an object against a specific { key: value } part of a query.
 */
function matchQueryPart(obj: any, queryKey: string, queryValue: any, treatObjAsValue?: boolean): boolean {
  const objValue = getDotValue(obj, queryKey);

  // Check if the value is an array if we don't force a treatment as value
  if (Array.isArray(objValue) && !treatObjAsValue) {
    // If the queryValue is an array, try to perform an exact match
    if (Array.isArray(queryValue)) return matchQueryPart(obj, queryKey, queryValue, true);

    // Check if we are using an array-specific comparison function
    if (queryValue !== null && typeof queryValue === 'object' && !isRegExp(queryValue)) {
      for (const key in queryValue) {
        if (Object.prototype.hasOwnProperty.call(queryValue, key) && arrayComparisonFunctions[key]) {
          return matchQueryPart(obj, queryKey, queryValue, true);
        }
      }
    }

    // If not, treat it as an array of { obj, query } where there needs to be at least one match
    for (const el of objValue) {
      if (matchQueryPart({ k: el }, 'k', queryValue)) return true; // k here could be any string
    }
    return false;
  }

  // queryValue is an actual object. Determine whether it contains comparison operators
  // or only normal fields. Mixed objects are not allowed
  if (queryValue !== null && typeof queryValue === 'object' && !isRegExp(queryValue) && !Array.isArray(queryValue)) {
    const keys = Object.keys(queryValue);
    const firstChars = keys.map(item => item[0]);
    const dollarFirstChars = firstChars.filter(c => c === '$');

    if (dollarFirstChars.length !== 0 && dollarFirstChars.length !== firstChars.length)
      throw new Error('You cannot mix operators and normal fields');

    // queryValue is an object of this form: { $comparisonOperator1: value1, ... }
    if (dollarFirstChars.length > 0) {
      for (const key of keys) {
        if (!comparisonFunctions[key]) throw new Error(`Unknown comparison function ${key}`);

        if (!comparisonFunctions[key](objValue, queryValue[key])) return false;
      }
      return true;
    }
  }

  // Using regular expressions with basic querying
  if (isRegExp(queryValue)) return comparisonFunctions.$regex(objValue, queryValue);

  // queryValue is either a native value or a normal object
  // Basic matching is possible
  return areThingsEqual(objValue, queryValue);
}
